# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6332fc4775b4991d04579bde3631d9b5e8720065613124e6c3e85212d89157b62c9e8db717c28fd782c02a1f38ae503d4f5a5eb4af17f031372d85487b15fc56

test:
  secret_key_base: 08bd92d0f1bbe77857bd2e269cce22f6fdf4670c63eb7705c7fdfbe45febf9643854d30b8c7bb3f2075ac0bfa20536940cd6c1f8a6a544fcb6aef705f2f6683e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
